### ISSUE TITLE
About Siam Projection

### ISSUE THREAD

**Issue by lsyysl9711** [HICAI-ZJU/iMoLD#2]
https://github.com/HICAI-ZJU/iMoLD/blob/6d244521a19a6e4a6ef7e4a2356cc29ab1cf9917/models/model.py#L93

Thanks for sharing the codes!

But I am confused about one part: It seems that the projection layer in the Encoder isn't used anywhere in the code. Did I miss something?

**Comment by toooooodo** [comment]
This is the old version of the code and I forgot to remove it. Please ignore it.
