### ISSUE TITLE
requests.exceptions.ConnectionError:

### ISSUE THREAD

**Issue by yang-W517** [HICAI-ZJU/iMoLD#3]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1GNc0HUee5YQH4Vtlk8ZbDjyJBYTEyabo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc3f5ebb0a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Can you tell me how to solve it?

**Comment by toooooodo** [comment]
Hello, this seems to be the reason for the internet connection, please check if the internet connection is working.

**Comment by yang-W517** [comment]
I get it,thanks for your help.
